dev-deployment:
 variables:
   GIT_STRATEGY: fetch
 script:
   - bash ~/gitlab/deploylaravelproject11.sh
 environment:
     name: Development
     url : https://fitness-healthcare.dedicateddevelopers.us/
 tags:
   - custom-laravel
 only:
   - dev
